/*
 * Image Processing API
 * Applies a sequence of transformations to an image
 *
 * OpenAPI spec version: 1.0
 * Contact: ahtran@seattleu.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.seattleu.imageprocessor.client.api;

import com.seattleu.imageprocessor.client.model.EntityModelImageProcessingDetail;
import com.seattleu.imageprocessor.client.model.ImageProcessingDetail;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImageProcessorControllerApi
 */
@Ignore
public class ImageProcessorControllerApiTest {

    private final ImageProcessorControllerApi api = new ImageProcessorControllerApi();

    
    /**
     * Performs a sequence of transformations as specified in the request body
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transformImageUsingPOSTTest() {
        ImageProcessingDetail imageProcessingDetail = null;
        EntityModelImageProcessingDetail response = api.transformImageUsingPOST(imageProcessingDetail);

        // TODO: test validations
    }
    
}
