/*
 * Image Processing API
 * Applies a sequence of transformations to an image
 *
 * OpenAPI spec version: 1.0
 * Contact: ahtran@seattleu.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.seattleu.imageprocessor.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OperationHandlerApi
 */
@Ignore
public class OperationHandlerApiTest {

    private final OperationHandlerApi api = new OperationHandlerApi();

    
    /**
     * handle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void handleUsingGETTest() {
        Object body = null;
        Object response = api.handleUsingGET(body);

        // TODO: test validations
    }
    
    /**
     * handle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void handleUsingGET1Test() {
        Object body = null;
        Object response = api.handleUsingGET1(body);

        // TODO: test validations
    }
    
    /**
     * handle
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void handleUsingGET2Test() {
        Object body = null;
        Object response = api.handleUsingGET2(body);

        // TODO: test validations
    }
    
}
