/*
 * Image Processing API
 * Applies a sequence of transformations to an image
 *
 * OpenAPI spec version: 1.0
 * Contact: ahtran@seattleu.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.seattleu.imageprocessor.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebMvcLinksHandlerApi
 */
@Ignore
public class WebMvcLinksHandlerApiTest {

    private final WebMvcLinksHandlerApi api = new WebMvcLinksHandlerApi();

    
//    /**
//     * links
//     *
//     *
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void linksUsingGETTest() {
//        Map<String, Map<String, Link>> response = api.linksUsingGET();
//
//        // TODO: test validations
//    }
    
}
